default_mp3_download_path = "temp/download.mp3"
default_ogg_download_path = "temp/download.ogg"
default_cache_path = "temp/"
currentA_path = "../ices-docker/music/currentA.ogg"
currentB_path = "../ices-docker/music/currentB.ogg"